def build(bld):
    program = bld.create_ns3_program(
        'satcompute',
        ['core', 'network', 'csma', 'point-to-point', 'internet',
         'applications', 'flow-monitor'])
    program.source = [
        'satcompute.cc',
        'para.cc',
        'topo.cc',
        'jsontopo/topo-json.cc',
        'jsontopo/topo-link-state.cc',
        'metrics/metrics.cc',
    ]
