def build(bld):
    program = bld.create_ns3_program(
        'satcompute',
        ['core', 'network', 'csma', 'point-to-point', 'internet',
         'applications', 'flow-monitor'])
    program.source = [
        'satcompute.cc',
        'para.cc',
        'topo.cc',
        'jsontopo/topo-json.cc',
        'jsontopo/topo-link-state.cc',
        'metrics/metrics.cc',
        'routing/satcompute-ipv4-global-routing.cc',
        'routing/satcompute-ipv4-global-routing-helper.cc',
        'traffic/background-traffic.cc',
        'traffic/network-transfer.cc',
        'traffic/network-transfer-application.cc',
        'traffic/network-transfer-config.cc',
        'traffic/network-transfer-receiver.cc',
    ]
