# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('cluster', ['core','network','point-to-point'])
    module.source = [
        'model/dynamic-cluster.cc',
        'model/link-utilization.cc',
        'model/betweenness-centrality.cc',
        'model/fault-judgment.cc'
        #'helper/cluster-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('cluster')
    module_test.source = [
        # 'test/cluster-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/cluster-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'cluster'
    headers.source = [
        'model/dynamic-cluster.h',
        'model/link-utilization.h',
        'model/betweenness-centrality.h',
        'model/fault-judgment.h'
        #'helper/cluster-helper.h',
        ]

    # if bld.env.ENABLE_EXAMPLES:
    #     bld.recurse('examples')

    # bld.ns3_python_bindings()

