## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
   obj = bld.create_ns3_program('openflow-sdn-switch-test',
                                ['openflow', 'csma', 'antenna', 'mobility', 'internet', 'applications', 'netanim', 'point-to-point', 'cluster', 'flow-monitor'])
   obj.source = ['openflow-sdn-switch-test.cc', 'swtch.cc', 'topo.cc', 'all-node.cc', 'para.cc', 'cluster.cc', 'satrouting.cc', 'access.cc']
   # obj.source = ['openflow-sdn-switch-test.cc', 'swtch.cc', 'topo.cc', 'all-node.cc', 'para.cc', 'cluster.cc']

   obj = bld.create_ns3_program('hydra-sim',
                                ['openflow', 'csma', 'antenna', 'mobility', 'internet', 'applications', 'netanim', 'point-to-point', 'cluster', 'flow-monitor'])
   obj.source = ['hydra-sim.cc', 'swtch.cc', 'topo.cc', 'all-node.cc', 'para.cc', 'cluster.cc', 'satrouting.cc', 'access.cc']

   obj = bld.create_ns3_program('ospf',
                                ['openflow','csma', 'antenna', 'mobility', 'internet', 'applications', 'netanim', 'point-to-point','flow-monitor', 'cluster'])
   obj.source = ['ospf.cc']

   # 添加头文件搜索路径
   obj.include = ['./', ]

